services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  drugs:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/drugs
      - CONFIG_PATH=/config.yaml
      - LISTEN_ADDR=:8080
    depends_on:
      - mongodb

volumes:
  mongo-data:
