// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cache/status": {
            "get": {
                "description": "Returns per-slug cache health including staleness, TTL remaining, and health score.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Cache status overview",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.CacheStatusResponse"
                        }
                    }
                }
            }
        },
        "/api/cache/{slug}": {
            "get": {
                "description": "Returns cached upstream API data. Fetches from upstream if not cached.\nThe response data shape depends on the upstream API. For example, the\n` + "`" + `drugclasses` + "`" + ` endpoint returns objects with fields: ` + "`" + `name` + "`" + ` (string),\n` + "`" + `type` + "`" + ` (string), ` + "`" + `code` + "`" + ` (string), ` + "`" + `codingSystem` + "`" + ` (string).\nAvailable query parameters vary by endpoint — use ` + "`" + `GET /api/endpoints` + "`" + `\nto discover each endpoint's supported params (e.g. BRAND_NAME, GENERIC_NAME,\nNDC, PHARM_CLASS for fda-ndc; SETID for spl-detail).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Get cached data for an endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint slug from config",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Path parameter value (varies by endpoint)",
                        "name": "SETID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Force upstream refresh (true/false)",
                        "name": "_force",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service overloaded or upstream circuit open",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/cache/{slug}/_meta": {
            "get": {
                "description": "Returns lightweight cache state (staleness, TTL, record count, circuit state) for a single slug without transferring the data payload.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Per-slug cache metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint slug from config",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.SlugMeta"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/cache/{slug}/bulk": {
            "post": {
                "description": "Looks up multiple cache keys in a single request. Cache-only — does not trigger upstream fetches.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Bulk cache lookup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint slug from config",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Batch of queries",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.bulkQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.BulkQueryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/config/validate": {
            "post": {
                "description": "Validates a YAML config snippet for structure and required fields without fetching from upstream.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Validate config YAML",
                "parameters": [
                    {
                        "description": "YAML config to validate",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.configValidateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.configValidateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.configValidateErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/endpoints": {
            "get": {
                "description": "Returns all configured upstream API endpoints with their metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "List configured endpoints",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handler.EndpointInfo"
                            }
                        }
                    }
                }
            }
        },
        "/api/test-fetch": {
            "post": {
                "description": "Fetches one page from an upstream API without caching. Used to validate endpoint configs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "summary": "Test-fetch dry run",
                "parameters": [
                    {
                        "description": "Endpoint configuration to test",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.testFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.testFetchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.testFetchErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/warmup": {
            "post": {
                "description": "Triggers background warm-up of cached endpoints. With no body, warms all scheduled endpoints. With {\"slugs\": [...]}, warms specific slugs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Trigger cache warmup",
                "parameters": [
                    {
                        "description": "Optional slug filter",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Warmup started",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid slug",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status including database connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Degraded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/openapi.json": {
            "get": {
                "description": "Returns the OpenAPI 3.0 JSON specification for this API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "OpenAPI specification",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns whether the service has finished warming its cache.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "Ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Warming",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns build metadata, runtime info, and uptime for deployment verification.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Version and build info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.VersionInfo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_finish06_cash-drugs_internal_model.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ResponseMeta"
                }
            }
        },
        "github_com_finish06_cash-drugs_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "request_id": {
                    "type": "string"
                },
                "retry_after": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "upstream_status": {
                    "type": "integer"
                }
            }
        },
        "github_com_finish06_cash-drugs_internal_model.ResponseMeta": {
            "type": "object",
            "properties": {
                "fetched_at": {
                    "type": "string"
                },
                "page_count": {
                    "type": "integer"
                },
                "results_count": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                },
                "stale_reason": {
                    "type": "string"
                }
            }
        },
        "internal_handler.BulkQueryResponse": {
            "type": "object",
            "properties": {
                "duration_ms": {
                    "type": "integer"
                },
                "errors": {
                    "type": "integer"
                },
                "hits": {
                    "type": "integer"
                },
                "misses": {
                    "type": "integer"
                },
                "request_id": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler.BulkQueryResult"
                    }
                },
                "slug": {
                    "type": "string"
                },
                "total_queries": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.BulkQueryResult": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ResponseMeta"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "description": "\"hit\", \"miss\", \"error\"",
                    "type": "string"
                }
            }
        },
        "internal_handler.CacheStatusInfo": {
            "type": "object",
            "properties": {
                "cached": {
                    "type": "boolean"
                },
                "is_stale": {
                    "type": "boolean"
                },
                "last_refreshed": {
                    "type": "string"
                }
            }
        },
        "internal_handler.CacheStatusResponse": {
            "type": "object",
            "properties": {
                "generated_at": {
                    "type": "string"
                },
                "healthy_slugs": {
                    "type": "integer"
                },
                "slugs": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/internal_handler.SlugStatus"
                    }
                },
                "stale_slugs": {
                    "type": "integer"
                },
                "total_slugs": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.EndpointInfo": {
            "type": "object",
            "properties": {
                "cache_status": {
                    "$ref": "#/definitions/internal_handler.CacheStatusInfo"
                },
                "example_url": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "pagination": {
                    "type": "boolean"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler.ParamInfo"
                    }
                },
                "path": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "scheduled": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                },
                "ttl": {
                    "type": "string"
                }
            }
        },
        "internal_handler.ParamInfo": {
            "type": "object",
            "properties": {
                "example": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "required": {
                    "type": "boolean"
                },
                "type": {
                    "description": "\"path\", \"query\", or \"search\"",
                    "type": "string"
                }
            }
        },
        "internal_handler.SlugMeta": {
            "type": "object",
            "properties": {
                "circuit_state": {
                    "description": "\"closed\", \"open\", \"half-open\"",
                    "type": "string"
                },
                "has_params": {
                    "description": "true if endpoint has parameterized paths",
                    "type": "boolean"
                },
                "has_schedule": {
                    "description": "true if refresh cron is configured",
                    "type": "boolean"
                },
                "is_stale": {
                    "description": "true if past TTL or never cached",
                    "type": "boolean"
                },
                "last_refreshed": {
                    "description": "ISO 8601 or null",
                    "type": "string"
                },
                "page_count": {
                    "description": "from cached response metadata",
                    "type": "integer"
                },
                "record_count": {
                    "description": "total items across all pages",
                    "type": "integer"
                },
                "schedule": {
                    "description": "cron expression or null",
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "ttl_remaining": {
                    "description": "duration string, \"0s\" if stale",
                    "type": "string"
                }
            }
        },
        "internal_handler.SlugStatus": {
            "type": "object",
            "properties": {
                "configured": {
                    "type": "boolean"
                },
                "has_schedule": {
                    "type": "boolean"
                },
                "health": {
                    "type": "integer"
                },
                "is_stale": {
                    "type": "boolean"
                },
                "last_refresh": {
                    "type": "string"
                },
                "schedule": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "ttl_remaining": {
                    "type": "string"
                }
            }
        },
        "internal_handler.VersionInfo": {
            "type": "object",
            "properties": {
                "arch": {
                    "type": "string"
                },
                "build_date": {
                    "type": "string"
                },
                "endpoint_count": {
                    "type": "integer"
                },
                "git_branch": {
                    "type": "string"
                },
                "git_commit": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "gomaxprocs": {
                    "type": "integer"
                },
                "hostname": {
                    "type": "string"
                },
                "leader": {
                    "type": "boolean"
                },
                "os": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "uptime_seconds": {
                    "type": "number"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_handler.bulkQueryItem": {
            "type": "object",
            "properties": {
                "params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handler.bulkQueryRequest": {
            "type": "object",
            "properties": {
                "queries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler.bulkQueryItem"
                    }
                }
            }
        },
        "internal_handler.configValidateEndpoint": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "has_pagination": {
                    "type": "boolean"
                },
                "has_schedule": {
                    "type": "boolean"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_handler.configValidateErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler.configValidateRequest": {
            "type": "object",
            "properties": {
                "yaml": {
                    "type": "string"
                }
            }
        },
        "internal_handler.configValidateResponse": {
            "type": "object",
            "properties": {
                "endpoint_count": {
                    "type": "integer"
                },
                "endpoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_handler.configValidateEndpoint"
                    }
                },
                "request_id": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_handler.testFetchErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "error_code": {
                    "type": "string"
                },
                "fetch_duration_ms": {
                    "type": "integer"
                },
                "request_id": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_handler.testFetchRequest": {
            "type": "object",
            "properties": {
                "base_url": {
                    "type": "string"
                },
                "data_key": {
                    "type": "string"
                },
                "flatten": {
                    "type": "boolean"
                },
                "format": {
                    "type": "string"
                },
                "pagesize": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "query_params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "search_params": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_key": {
                    "type": "string"
                }
            }
        },
        "internal_handler.testFetchResponse": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "data_preview": {},
                "fetch_duration_ms": {
                    "type": "integer"
                },
                "page_count_estimate": {
                    "type": "integer"
                },
                "request_id": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "total_results": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.10.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "cash-drugs API",
	Description:      "API cache/proxy — fetches from upstream REST APIs, stores in MongoDB, serves cached data to internal consumers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
