// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/cache/{slug}": {
            "get": {
                "description": "Returns cached upstream API data. Fetches from upstream if not cached.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cache"
                ],
                "summary": "Get cached data for an endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Endpoint slug from config",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Path parameter value (varies by endpoint)",
                        "name": "SETID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Force upstream refresh (true/false)",
                        "name": "_force",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service overloaded or upstream circuit open",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/endpoints": {
            "get": {
                "description": "Returns all configured upstream API endpoints with their metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "List configured endpoints",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_handler.EndpointInfo"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status including database connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Degraded",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/openapi.json": {
            "get": {
                "description": "Returns the OpenAPI 3.0 JSON specification for this API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "OpenAPI specification",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns build metadata, runtime info, and uptime for deployment verification.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Version and build info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.VersionInfo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_finish06_cash-drugs_internal_model.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/github_com_finish06_cash-drugs_internal_model.ResponseMeta"
                }
            }
        },
        "github_com_finish06_cash-drugs_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "upstream_status": {
                    "type": "integer"
                }
            }
        },
        "github_com_finish06_cash-drugs_internal_model.ResponseMeta": {
            "type": "object",
            "properties": {
                "fetched_at": {
                    "type": "string"
                },
                "page_count": {
                    "type": "integer"
                },
                "results_count": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "source_url": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                },
                "stale_reason": {
                    "type": "string"
                }
            }
        },
        "internal_handler.EndpointInfo": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string"
                },
                "pagination": {
                    "type": "boolean"
                },
                "params": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "path": {
                    "type": "string"
                },
                "scheduled": {
                    "type": "boolean"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_handler.VersionInfo": {
            "type": "object",
            "properties": {
                "arch": {
                    "type": "string"
                },
                "build_date": {
                    "type": "string"
                },
                "endpoint_count": {
                    "type": "integer"
                },
                "git_branch": {
                    "type": "string"
                },
                "git_commit": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "gomaxprocs": {
                    "type": "integer"
                },
                "hostname": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "uptime_seconds": {
                    "type": "number"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.6.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "cash-drugs API",
	Description:      "API cache/proxy — fetches from upstream REST APIs, stores in MongoDB, serves cached data to internal consumers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
